export const packages = [
  {
    slug: 'char-dham-yatra',
    name: 'Char Dham Yatra',
    subtitle: 'The Ultimate Sacred Circuit of Uttarakhand',
    duration: '11 Days / 10 Nights',
    price: 24999,
    groupPrice: 21999,
    category: 'Char Dham',
    featured: true,
    badge: 'Most Popular',
    badgeColor: '#EE9B00',
    gradient: 'linear-gradient(135deg, #050a15, #001020)',
    accentColor: '#EE9B00',
    destinations: ['Haridwar', 'Rishikesh', 'Yamunotri', 'Gangotri', 'Kedarnath', 'Badrinath'],
    overview: `The Char Dham Yatra is the most revered pilgrimage circuit in Hinduism, encompassing the four sacred shrines of Yamunotri, Gangotri, Kedarnath, and Badrinath nestled in the Garhwal Himalayas of Uttarakhand. Hindu scriptures declare that undertaking this yatra washes away all sins and grants the pilgrim moksha — liberation from the cycle of birth and rebirth.

Sinatra Travels has been conducting Char Dham Yatra since 2008 with an impeccable track record. Our experienced team handles every aspect of your journey — from Haridwar to the high-altitude shrines and back — so you can focus entirely on your spiritual experience.`,
    highlights: [
      'All 4 sacred Dhams covered — Yamunotri, Gangotri, Kedarnath, Badrinath',
      'Experienced local guides at each shrine',
      'Comfortable AC transport throughout',
      'Helicopter option for Kedarnath available',
      'Temple-side hotel accommodations',
      'Vegetarian meals included (breakfast + dinner)',
      'Medical support and oxygen cylinders',
      'Special arrangements for senior pilgrims',
    ],
    itinerary: [
      { day: 1, title: 'Arrival at Haridwar', desc: 'Arrive Haridwar, hotel check-in, evening Ganga Aarti at Har Ki Pauri.' },
      { day: 2, title: 'Haridwar – Barkot', desc: 'Drive to Barkot via Rishikesh. Evening at leisure. Overnight Barkot.' },
      { day: 3, title: 'Barkot – Yamunotri – Barkot', desc: 'Trek to Yamunotri shrine (6km), darshan, return to Barkot.' },
      { day: 4, title: 'Barkot – Uttarkashi', desc: 'Drive through scenic mountain roads. Vishwanath temple visit.' },
      { day: 5, title: 'Uttarkashi – Gangotri – Uttarkashi', desc: 'Gangotri darshan, Suraj Kund, Bhagirathi Shila. Return.' },
      { day: 6, title: 'Uttarkashi – Guptkashi', desc: 'Drive to Guptkashi, Vishwanath temple, Ardhnareshwar temple.' },
      { day: 7, title: 'Kedarnath Trek', desc: 'Early morning 14km trek to Kedarnath. Evening aarti, overnight.' },
      { day: 8, title: 'Kedarnath – Badrinath', desc: 'Morning darshan, descend, drive to Badrinath via Joshimath.' },
      { day: 9, title: 'Badrinath Darshan', desc: 'Badrinath temple darshan, Tapt Kund, Mana village (last Indian village).' },
      { day: 10, title: 'Badrinath – Rishikesh', desc: 'Return drive to Rishikesh. Evening at Ram Jhula area.' },
      { day: 11, title: 'Rishikesh – Haridwar – Departure', desc: 'Triveni Ghat aarti, drive to Haridwar for departure.' },
    ],
    inclusions: ['AC Transport', 'Hotel Accommodation (twin/triple sharing)', 'Breakfast & Dinner', 'Guide charges', 'All temple permits', 'First aid kit', 'Oxygen cylinders'],
    exclusions: ['Airfare', 'Lunch', 'Pony/Palanquin charges at Kedarnath', 'Personal expenses', 'Insurance', 'Helicopter charges'],
    bestTime: 'May–June, September–October',
    difficulty: 'Moderate (Kedarnath trek 14km)',
    groupSize: '15–40 persons',
    departurePoint: 'Haridwar Railway Station',
    tags: ['Char Dham', 'Uttarakhand', 'Kedarnath', 'Badrinath', 'Himalaya'],
  },
  {
    slug: 'jyotirlinga-tour',
    name: '12 Jyotirlinga Tour Package',
    subtitle: 'Complete Circuit of All 12 Sacred Shiva Shrines',
    duration: '16 Days / 15 Nights',
    price: 34999,
    groupPrice: 29999,
    category: 'Jyotirlinga',
    featured: true,
    badge: 'Signature Tour',
    badgeColor: '#0A9396',
    gradient: 'linear-gradient(135deg, #001520, #000a10)',
    accentColor: '#0A9396',
    destinations: ['Ujjain', 'Omkareshwar', 'Somnath', 'Dwarka', 'Nageshwar', 'Trimbakeshwar', 'Bhimashankar', 'Grishneshwar', 'Aundha Nagnath', 'Parli Vaijnath', 'Mallikarjuna', 'Kedarnath', 'Kashi Vishwanath', 'Vaidyanath', 'Rameshwaram'],
    overview: `The 12 Jyotirlingas are the most sacred shrines of Lord Shiva, spread across India from Gujarat to Uttarakhand, from Maharashtra to Andhra Pradesh. Undertaking the complete Jyotirlinga circuit is considered the greatest act of Shiva devotion, believed to grant liberation from all worldly bondage.

Sinatra Travels is one of the few agencies in Indore that offers a comprehensive, well-planned 12 Jyotirlinga tour covering all sacred sites with experienced guides, comfortable transport, and authentic spiritual experience at each shrine.`,
    highlights: [
      'All 12 Jyotirlingas in one grand circuit',
      'Expert Shiva scripture guide throughout',
      'Special early morning darshan arranged',
      'VIP queue arrangements at major shrines',
      'Comfortable AC sleeper bus for long routes',
      'Stay at dharamshalas and pilgrimage hotels',
    ],
    itinerary: [
      { day: '1-2', title: 'Mahakaleshwar & Omkareshwar', desc: 'Ujjain Bhasma Aarti, Mahakaleshwar darshan. Drive to Omkareshwar.' },
      { day: '3-5', title: 'Gujarat Jyotirlingas', desc: 'Somnath, Nageshwar, Dwarkadhish temple visit and darshan.' },
      { day: '6-9', title: 'Maharashtra Circuit', desc: 'Trimbakeshwar, Bhimashankar, Grishneshwar, Aundha Nagnath, Parli Vaijnath.' },
      { day: '10-11', title: 'Srisailam', desc: 'Mallikarjuna Jyotirlinga and Bhramaramba Devi. River Ghat.' },
      { day: '12-13', title: 'Rameswaram', desc: 'Ramanathaswamy temple, 22 sacred theerthams, Dhanushkodi.' },
      { day: '14-15', title: 'Varanasi & Vaidyanath', desc: 'Kashi Vishwanath darshan, Ganga Aarti. Deoghar Vaidyanath.' },
      { day: '16', title: 'Return Journey', desc: 'Departure from Deoghar/Varanasi.' },
    ],
    inclusions: ['AC Transport (mix of bus & train)', 'All accommodations', 'Breakfast daily', 'All guide fees', 'Temple entry', 'Theertham charges at Rameswaram'],
    exclusions: ['Airfare', 'Lunch & Dinner', 'Personal expenses', 'Pony charges', 'Donations at temples'],
    bestTime: 'October–March',
    difficulty: 'Moderate',
    groupSize: '20–50 persons',
    departurePoint: 'Indore',
    tags: ['Jyotirlinga', 'Shiva', 'All India Tour', 'Spiritual'],
  },
  {
    slug: 'ujjain-omkareshwar-tour',
    name: 'Ujjain Omkareshwar Tour',
    subtitle: 'MP\'s Twin Jyotirlinga Weekend Special',
    duration: '3 Days / 2 Nights',
    price: 5999,
    groupPrice: 4999,
    category: 'Weekend Tour',
    featured: false,
    badge: 'Weekend Special',
    badgeColor: '#EE9B00',
    gradient: 'linear-gradient(135deg, #1a0800, #0a0500)',
    accentColor: '#EE9B00',
    destinations: ['Ujjain', 'Omkareshwar'],
    overview: 'Perfect for families and groups from Indore looking for a short, spiritually powerful weekend pilgrimage. Visit two of the most important Jyotirlingas — Mahakaleshwar in Ujjain and Omkareshwar in Khandwa — both within Madhya Pradesh, in a comfortable 3-day tour.',
    highlights: ['Ujjain Bhasma Aarti (4 AM)', 'Mahakaleshwar darshan', 'Omkareshwar island boat ride', 'Narmada Aarti', 'AC transport from Indore', 'All meals included'],
    itinerary: [
      { day: 1, title: 'Indore – Ujjain', desc: 'Evening departure. Ram Ghat, Kal Bhairav temple. Hotel check-in.' },
      { day: 2, title: 'Ujjain – Omkareshwar', desc: 'Pre-dawn Bhasma Aarti at 4 AM. After darshan, drive to Omkareshwar. Boat ride, darshan, Narmada Aarti.' },
      { day: 3, title: 'Omkareshwar – Indore', desc: 'Morning Mamleshwar darshan. Return to Indore by afternoon.' },
    ],
    inclusions: ['AC Transport', '2 nights hotel', 'All meals', 'Bhasma Aarti ticket', 'Guide', 'Boat ride'],
    exclusions: ['Personal expenses', 'Donations', 'Camera fees'],
    bestTime: 'Year-round (avoid peak summer)',
    difficulty: 'Easy',
    groupSize: '10–40 persons',
    departurePoint: 'Indore',
    tags: ['Weekend', 'Madhya Pradesh', 'Jyotirlinga', 'Short Tour'],
  },
  {
    slug: 'kashi-ayodhya-tour',
    name: 'Kashi Ayodhya Tour',
    subtitle: 'The Cities of Moksha and Ram',
    duration: '5 Days / 4 Nights',
    price: 12999,
    groupPrice: 10999,
    category: 'North India',
    featured: false,
    badge: 'Heritage Circuit',
    badgeColor: '#0A9396',
    gradient: 'linear-gradient(135deg, #1a1000, #0a0500)',
    accentColor: '#0A9396',
    destinations: ['Varanasi', 'Sarnath', 'Prayagraj', 'Ayodhya'],
    overview: 'A profound journey through two of India\'s most historically and spiritually significant cities — Varanasi, the eternal city of Shiva and moksha, and Ayodhya, the birthplace of Lord Ram. The new Ram Mandir at Ayodhya adds an especially powerful dimension to this tour.',
    highlights: ['Kashi Vishwanath Jyotirlinga darshan', 'Ganga Aarti at Dashashwamedh Ghat', 'Sarnath Buddhist site', 'Ram Janmabhoomi Mandir darshan', 'Hanuman Garhi', 'Saryu Ghat Aarti', 'Prayagraj Sangam'],
    itinerary: [
      { day: 1, title: 'Departure – Varanasi', desc: 'Night bus/train from Indore. Arrive Varanasi morning.' },
      { day: 2, title: 'Varanasi Darshan', desc: 'Kashi Vishwanath, Annapurna temple, Ganga boat ride, evening aarti.' },
      { day: 3, title: 'Sarnath & Prayagraj', desc: 'Sarnath Buddhist sites, drive to Prayagraj. Triveni Sangam dip.' },
      { day: 4, title: 'Ayodhya', desc: 'Ram Janmabhoomi, Hanuman Garhi, Kanak Bhavan, Saryu aarti.' },
      { day: 5, title: 'Return to Indore', desc: 'Departure from Ayodhya/Lucknow.' },
    ],
    inclusions: ['Transport (AC bus + train)', '4 nights accommodation', 'Breakfast', 'All guides', 'Boat ride at Varanasi'],
    exclusions: ['Airfare', 'Lunch & Dinner', 'Personal expenses'],
    bestTime: 'October–March',
    difficulty: 'Easy',
    groupSize: '15–45 persons',
    departurePoint: 'Indore',
    tags: ['Varanasi', 'Ayodhya', 'North India', 'Ram Mandir'],
  },
  {
    slug: 'vaishno-devi-tour',
    name: 'Vaishno Devi Tour Package',
    subtitle: 'Mata Ki Jai — Journey to the Trikuta Mountains',
    duration: '5 Days / 4 Nights',
    price: 13999,
    groupPrice: 11999,
    category: 'Shakti Peeth',
    featured: false,
    badge: 'Family Favourite',
    badgeColor: '#EE9B00',
    gradient: 'linear-gradient(135deg, #0a0020, #001015)',
    accentColor: '#EE9B00',
    destinations: ['Jammu', 'Katra', 'Vaishno Devi Shrine'],
    overview: 'One of the most beloved pilgrimage destinations in India, Vaishno Devi attracts over 8 million devotees every year. Our carefully designed tour ensures a comfortable and spiritually fulfilling experience — from Jammu\'s ancient temples to the sacred cave shrine of Mata Vaishno Devi in the Trikuta mountains.',
    highlights: ['Vaishno Devi cave shrine darshan', 'Banganga sacred pool', 'Ardhkuwari cave', 'Bhairavnath temple after darshan', 'Pony/Palki arrangements', 'Jammu Raghunath Temple', 'Comfortable Katra stay'],
    itinerary: [
      { day: 1, title: 'Indore – Jammu (Train)', desc: 'Overnight train to Jammu. Raghunath Temple darshan.' },
      { day: 2, title: 'Jammu – Katra', desc: 'Drive to Katra, yatra registration, Banganga visit, overnight.' },
      { day: 3, title: 'Vaishno Devi Trek', desc: '13km trek: Banganga – Ardhkuwari – Bhavan (cave shrine). Darshan.' },
      { day: 4, title: 'Bhairavnath – Katra', desc: 'Bhairavnath temple (mandatory after darshan). Descend to Katra.' },
      { day: 5, title: 'Return to Indore', desc: 'Train from Jammu to Indore.' },
    ],
    inclusions: ['Train tickets (Sleeper/3AC)', '4 nights accommodation', 'Breakfast & Dinner', 'Yatra registration', 'Guides'],
    exclusions: ['Pony/Palki charges', 'Helicopter', 'Lunch', 'Personal expenses'],
    bestTime: 'March–May, September–November',
    difficulty: 'Moderate (13km trek)',
    groupSize: '15–50 persons',
    departurePoint: 'Indore Railway Station',
    tags: ['Vaishno Devi', 'J&K', 'Shakti Peeth', 'Trek'],
  },
  {
    slug: 'tirupati-darshan-tour',
    name: 'Tirupati Darshan Tour',
    subtitle: 'Seek Blessings of the Richest God on Earth',
    duration: '5 Days / 4 Nights',
    price: 15999,
    groupPrice: 13499,
    category: 'South India',
    featured: false,
    badge: 'VIP Darshan',
    badgeColor: '#0A9396',
    gradient: 'linear-gradient(135deg, #1a0500, #0a0800)',
    accentColor: '#0A9396',
    destinations: ['Tirupati', 'Tirumala', 'Padmavathi Temple'],
    overview: 'Tirupati Balaji (Lord Venkateswara) is the most visited religious shrine in the world, receiving over 100,000 pilgrims daily. Our Tirupati darshan package is carefully designed to ensure you get a meaningful, queue-minimized darshan experience while also exploring the surrounding sacred sites.',
    highlights: ['VIP Special Entry Darshan ticket (₹300)', 'Padmavathi Temple Tiruchanur', 'Head tonsuring (mundan) facility', 'Prasadam (Laddu) arrangements', 'ISKCON Tirupati', 'Sri Kapileswara Temple'],
    itinerary: [
      { day: 1, title: 'Indore – Tirupati (Flight)', desc: 'Fly Indore–Bengaluru, connect to Tirupati. Hotel check-in.' },
      { day: 2, title: 'Padmavathi Temple & Tirumala', desc: 'Morning Padmavathi Temple. Afternoon ascend Tirumala.' },
      { day: 3, title: 'Tirupati Balaji Darshan', desc: 'Pre-dawn queue for VIP darshan. Post-darshan ISKCON visit.' },
      { day: 4, title: 'Chandragiri Fort & Departure', desc: 'Chandragiri Fort, local sightseeing, evening return flight.' },
      { day: 5, title: 'Return to Indore', desc: 'Arrive Indore.' },
    ],
    inclusions: ['Return flights (Indore–Tirupati)', '4 nights hotel', 'All meals veg', 'VIP darshan tickets', 'All local transport', 'Guide'],
    exclusions: ['Tonsuring charges', 'Laddu charges', 'Personal expenses'],
    bestTime: 'October–February',
    difficulty: 'Easy',
    groupSize: '10–30 persons',
    departurePoint: 'Indore Airport',
    tags: ['Tirupati', 'South India', 'VIP Darshan', 'Flight Package'],
  },
  {
    slug: 'rameswaram-spiritual-tour',
    name: 'Rameswaram Spiritual Tour',
    subtitle: 'Where Ram Prayed to Shiva',
    duration: '6 Days / 5 Nights',
    price: 16999,
    groupPrice: 14499,
    category: 'South India',
    featured: false,
    badge: 'Char Dham',
    badgeColor: '#005F73',
    gradient: 'linear-gradient(135deg, #1a0800, #001015)',
    accentColor: '#005F73',
    destinations: ['Madurai', 'Rameswaram', 'Dhanushkodi', 'Kanyakumari'],
    overview: 'Rameswaram, on Pamban Island in Tamil Nadu, is where Lord Ram is believed to have built the bridge to Lanka and worshipped Lord Shiva for victory. The Ramanathaswamy temple houses the longest temple corridor in India and the mandatory 22-theertham ritual bath is a uniquely purifying experience.',
    highlights: ['Ramanathaswamy Temple (22 theerthams)', 'Dhanushkodi ghost town', 'Adam\'s Bridge view', 'Meenakshi Amman Temple Madurai', 'Kanyakumari sunrise/sunset', 'Pamban Bridge drive'],
    itinerary: [
      { day: 1, title: 'Indore – Madurai (Train/Flight)', desc: 'Arrive Madurai. Rest.' },
      { day: 2, title: 'Meenakshi Amman Temple', desc: 'Madurai Meenakshi temple. Evening Alangaram. Night train to Rameswaram.' },
      { day: 3, title: 'Rameswaram Darshan', desc: '22 theertham ritual bath. Ramanathaswamy temple darshan. Dhanushkodi.' },
      { day: 4, title: 'Kanyakumari', desc: 'Drive to Kanyakumari. Vivekananda Rock, Thiruvalluvar Statue, sunrise.' },
      { day: 5, title: 'Return Journey', desc: 'Depart Kanyakumari / Trivandrum.' },
      { day: 6, title: 'Arrive Indore', desc: 'Reach Indore.' },
    ],
    inclusions: ['Train/flight tickets', '5 nights accommodation', 'Breakfast & Dinner', 'Theertham entry charges', 'All local transport', 'Guide'],
    exclusions: ['Lunch', 'Boat tickets at Kanyakumari', 'Personal expenses'],
    bestTime: 'October–April',
    difficulty: 'Easy',
    groupSize: '15–45 persons',
    departurePoint: 'Indore',
    tags: ['Rameswaram', 'South India', 'Char Dham', 'Tamil Nadu'],
  },
  {
    slug: 'gujarat-temple-tour',
    name: 'Gujarat Temple Tour',
    subtitle: 'Somnath, Dwarka, Nageshwar & Ambaji',
    duration: '6 Days / 5 Nights',
    price: 13999,
    groupPrice: 11999,
    category: 'West India',
    featured: false,
    badge: 'Gujarat Circuit',
    badgeColor: '#EE9B00',
    gradient: 'linear-gradient(135deg, #1a1000, #0a0500)',
    accentColor: '#EE9B00',
    destinations: ['Somnath', 'Dwarka', 'Nageshwar', 'Ambaji', 'Rani Ki Vav'],
    overview: 'Gujarat is home to some of India\'s most important Jyotirlingas and sacred sites. Our Gujarat Temple Tour covers Somnath (first Jyotirlinga), Dwarkadhish (Char Dham), Nageshwar Jyotirlinga, Ambaji Shakti Peeth, and the UNESCO heritage site of Rani Ki Vav — all in a comfortable 6-day circuit.',
    highlights: ['Somnath Jyotirlinga (1st)', 'Dwarkadhish Temple (Char Dham)', 'Nageshwar Jyotirlinga', 'Ambaji Shakti Peeth', 'Somnath Light & Sound Show', 'Arabian Sea sunset'],
    itinerary: [
      { day: 1, title: 'Indore – Somnath (Train)', desc: 'Overnight journey. Arrive Somnath.' },
      { day: 2, title: 'Somnath', desc: 'Temple darshan, Light & Sound show in evening.' },
      { day: 3, title: 'Somnath – Dwarka', desc: 'Drive via Porbandar (Gandhi birthplace). Dwarkadhish evening aarti.' },
      { day: 4, title: 'Dwarka & Nageshwar', desc: 'Nageshwar Jyotirlinga, Rukmini Temple, Beyt Dwarka island.' },
      { day: 5, title: 'Ambaji – Rani Ki Vav', desc: 'Drive north, Ambaji temple, Rani Ki Vav UNESCO site, Patan.' },
      { day: 6, title: 'Return to Indore', desc: 'Train/bus home.' },
    ],
    inclusions: ['Transport', '5 nights stay', 'Breakfast & Dinner', 'All guides', 'Entry tickets'],
    exclusions: ['Boat ride at Beyt Dwarka', 'Light show ticket', 'Personal expenses'],
    bestTime: 'October–March',
    difficulty: 'Easy',
    groupSize: '15–50 persons',
    departurePoint: 'Indore',
    tags: ['Gujarat', 'Somnath', 'Dwarka', 'Jyotirlinga'],
  },
  {
    slug: 'south-india-temple-circuit',
    name: 'South India Temple Circuit',
    subtitle: 'The Divine Dravidian Trail',
    duration: '10 Days / 9 Nights',
    price: 27999,
    groupPrice: 24999,
    category: 'South India',
    featured: true,
    badge: 'Grand Circuit',
    badgeColor: '#0A9396',
    gradient: 'linear-gradient(135deg, #001520, #000a08)',
    accentColor: '#0A9396',
    destinations: ['Tirupati', 'Rameswaram', 'Madurai', 'Srisailam', 'Kanyakumari'],
    overview: 'South India is the heartland of Dravidian temple architecture, with towering gopurams, intricate carvings, and temples that have stood for over 2,000 years. Our South India Temple Circuit covers the most significant shrines across Andhra Pradesh, Tamil Nadu, and Kerala in a comprehensive 10-day journey.',
    highlights: ['Tirupati VIP Darshan', 'Rameswaram 22 theerthams', 'Meenakshi Amman Madurai', 'Srisailam Jyotirlinga', 'Kanyakumari sunrise', 'Padmanabhaswamy Temple Trivandrum'],
    itinerary: [
      { day: '1-2', title: 'Tirupati', desc: 'Padmavathi temple, Tirumala VIP darshan.' },
      { day: '3-4', title: 'Srisailam', desc: 'Mallikarjuna Jyotirlinga, Bhramaramba Devi.' },
      { day: '5-6', title: 'Madurai & Rameswaram', desc: 'Meenakshi Amman, drive to Rameswaram, theerthams, darshan.' },
      { day: '7-8', title: 'Kanyakumari & Trivandrum', desc: 'Vivekananda Rock, Padmanabhaswamy Temple.' },
      { day: '9-10', title: 'Return', desc: 'Departure from Trivandrum/Coimbatore.' },
    ],
    inclusions: ['Flights (Indore–Tirupati, Trivandrum–Indore)', '9 nights hotel', 'All meals veg', 'All transport', 'All guides', 'VIP darshan'],
    exclusions: ['Boat charges', 'Camera fees', 'Personal expenses'],
    bestTime: 'October–March',
    difficulty: 'Easy to Moderate',
    groupSize: '15–40 persons',
    departurePoint: 'Indore Airport',
    tags: ['South India', 'Tamil Nadu', 'Andhra', 'Temple Circuit'],
  },
  {
    slug: 'uttarakhand-pilgrimage-package',
    name: 'Uttarakhand Pilgrimage Package',
    subtitle: 'Haridwar, Rishikesh, Kedarnath & More',
    duration: '7 Days / 6 Nights',
    price: 17999,
    groupPrice: 14999,
    category: 'North India',
    featured: false,
    badge: 'Himalayan Special',
    badgeColor: '#005F73',
    gradient: 'linear-gradient(135deg, #050a15, #000510)',
    accentColor: '#005F73',
    destinations: ['Haridwar', 'Rishikesh', 'Kedarnath', 'Badrinath'],
    overview: 'Uttarakhand — Devbhoomi (Land of Gods) — is home to the most sacred pilgrimage sites in North India. This 7-day tour covers the gateway cities of Haridwar and Rishikesh and reaches the high-altitude shrines of Kedarnath and Badrinath in the Garhwal Himalayas.',
    highlights: ['Har Ki Pauri Ganga Aarti', 'Rishikesh ashram experience', 'Kedarnath trek & darshan', 'Badrinath temple & Mana village', 'Valley views', 'Neelkanth Mahadev'],
    itinerary: [
      { day: '1-2', title: 'Haridwar & Rishikesh', desc: 'Ganga Aarti. Rishikesh — Ram Jhula, Laxman Jhula, ashrams.' },
      { day: '3-4', title: 'Kedarnath', desc: 'Drive Guptkashi. Trek to Kedarnath. Darshan. Return.' },
      { day: '5-6', title: 'Badrinath', desc: 'Drive to Badrinath. Tapt Kund. Temple darshan. Mana village.' },
      { day: 7, title: 'Return', desc: 'Drive to Haridwar/Rishikesh for departure.' },
    ],
    inclusions: ['AC Transport', '6 nights hotel', 'Breakfast & Dinner', 'Guide', 'Permits'],
    exclusions: ['Pony/Palki Kedarnath', 'Helicopter', 'Lunch', 'Personal'],
    bestTime: 'May–June, September–October',
    difficulty: 'Moderate',
    groupSize: '15–40 persons',
    departurePoint: 'Haridwar',
    tags: ['Uttarakhand', 'Char Dham', 'Himalaya', 'Kedarnath'],
  },
  {
    slug: 'mathura-vrindavan-package',
    name: 'Mathura Vrindavan Package',
    subtitle: 'Walk in the Footsteps of Lord Krishna',
    duration: '4 Days / 3 Nights',
    price: 8999,
    groupPrice: 7499,
    category: 'North India',
    featured: false,
    badge: 'Krishna Dham',
    badgeColor: '#EE9B00',
    gradient: 'linear-gradient(135deg, #0a1520, #050a10)',
    accentColor: '#EE9B00',
    destinations: ['Mathura', 'Vrindavan', 'Govardhan', 'Barsana', 'Gokul'],
    overview: 'The Braj region around Mathura and Vrindavan is the most sacred land for Vaishnava devotees. Every lane here echoes with Krishna\'s childhood stories. From the Krishna Janmabhoomi to the 5,000 temples of Vrindavan, from Govardhan Hill to the Gopi village of Barsana — this is a journey into the heart of devotion.',
    highlights: ['Krishna Janmabhoomi Temple', 'Vrindavan Banke Bihari Temple', 'ISKCON Vrindavan', 'Prem Mandir', 'Govardhan Hill Parikrama', 'Barsana Radha Temple', 'Yamuna Aarti'],
    itinerary: [
      { day: 1, title: 'Indore – Mathura', desc: 'Overnight train. Arrive morning. Krishna Janmabhoomi, Dwarkadheesh Temple.' },
      { day: 2, title: 'Vrindavan', desc: 'Banke Bihari, ISKCON, Prem Mandir, Rangji Temple.' },
      { day: 3, title: 'Govardhan & Barsana', desc: 'Govardhan parikrama. Barsana Radha temple. Nandgaon.' },
      { day: 4, title: 'Return to Indore', desc: 'Morning Yamuna Aarti. Departure.' },
    ],
    inclusions: ['Train tickets', '3 nights hotel', 'Breakfast', 'Guide', 'Local transport'],
    exclusions: ['Lunch & Dinner', 'ISKCON entry', 'Personal'],
    bestTime: 'October–March (Holi in March is spectacular)',
    difficulty: 'Easy',
    groupSize: '10–45 persons',
    departurePoint: 'Indore Railway Station',
    tags: ['Mathura', 'Vrindavan', 'Krishna', 'North India'],
  },
  {
    slug: 'jagannath-puri-tour',
    name: 'Jagannath Puri Tour',
    subtitle: 'Lord Jagannath\'s Coastal Abode — Odisha',
    duration: '5 Days / 4 Nights',
    price: 13499,
    groupPrice: 11499,
    category: 'East India',
    featured: false,
    badge: 'Char Dham',
    badgeColor: '#0A9396',
    gradient: 'linear-gradient(135deg, #001015, #000508)',
    accentColor: '#0A9396',
    destinations: ['Puri', 'Bhubaneswar', 'Konark'],
    overview: 'Jagannath Puri, the sacred coastal city of Odisha, is one of the four Char Dham sites and home to the magnificent Lord Jagannath temple. Combined with the architectural marvel of Konark Sun Temple and the beautiful temples of Bhubaneswar, this tour offers a complete Odishan spiritual and cultural experience.',
    highlights: ['Jagannath Temple (Mahaprasad)', 'Puri Beach', 'Konark Sun Temple (UNESCO)', 'Lingaraj Temple Bhubaneswar', 'Chilika Lake flamingos', 'Rath Yatra (if visiting July)'],
    itinerary: [
      { day: 1, title: 'Indore – Bhubaneswar (Flight)', desc: 'Arrive. Lingaraj Temple, Rajarani Temple, Mukteshwar Temple.' },
      { day: 2, title: 'Puri', desc: 'Drive to Puri. Jagannath Temple darshan, Mahaprasad, beach.' },
      { day: 3, title: 'Konark & Chilika', desc: 'Konark Sun Temple. Chilika Lake bird sanctuary.' },
      { day: 4, title: 'Puri – Bhubaneswar', desc: 'Shopping, Udayagiri & Khandagiri caves.' },
      { day: 5, title: 'Return to Indore', desc: 'Flight home.' },
    ],
    inclusions: ['Return flights', '4 nights hotel', 'All meals veg', 'Local transport', 'Guides', 'Mahaprasad arrangement'],
    exclusions: ['Boat at Chilika', 'Camera fees', 'Personal expenses'],
    bestTime: 'October–March',
    difficulty: 'Easy',
    groupSize: '10–40 persons',
    departurePoint: 'Indore Airport',
    tags: ['Puri', 'Odisha', 'Char Dham', 'East India'],
  },
]

export const getPackageBySlug = (slug) => packages.find(p => p.slug === slug)